export const MenuItems=[
    {
        title:'HOME',
        url:'#',
        cname:'nav-links'
    },
    {
        title:'GAME',
        url:'#',
        cname:'nav-links'
    },
    {
        title:'RELAX',
        url:'#',
        cname:'nav-links'
    },
    {
        title:'FITNESS',
        url:'#',
        cname:'nav-links'
    },
    {
        title:'SIGNUP',
        url:'#',
        cname:'nav-links-mobile'
    }
]